[package]
name = "git-branch-deleter"
version = "0.1.1"
authors = ["Dusan Malusev <malusevd99@gmail.com>"]
edition = "2018"

[dependencies]
git2 = "0.13"
clap = "2.33"
chrono = "0.4"
crossterm = "0.19"
rpassword = "^5"

[dev-dependencies]
mockall = "^0.9"
