name: 'Release'

on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
  macos:
    needs: release
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: Setup Rust and Cargo
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
      - name: Building Macos Binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.upload_url }}
          asset_path: ./target/release/git-branch-deleter
          asset_name: git-branch-deleter-macos-${{ github.ref }}
          asset_content_type: application/octet-stream
  ubuntu:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: Setup Rust and Cargo
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
      - name: Building Ubuntu Binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.upload_url }}
          asset_path: ./target/release/git-branch-deleter
          asset_name: git-branch-deleter-ubuntu-${{ github.ref }}
          asset_content_type: application/octet-stream
  windows:
    runs-on: windows-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: Setup Rust and Cargo
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
      - name: Building Windows Binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.upload_url }}
          asset_path: ./target/release/git-branch-deleter.exe
          asset_name: git-branch-deleter-windows-${{ github.ref }}.exe
          asset_content_type: application/octet-stream
